### PR TITLE
added transform `StringValue:ToArray`

### PR DESCRIPTION
**Pull request by eightBitter**
This is related to #110 . This transform is modeled after `Explode::RowsFromMultivalField`. I know we talked about potentially putting this transform in another module which seems fine to me. I put it in `Explode` for now because of its association with `RowsFromMultivalField`.

### CODE REVIEW

**Comment by kspurgin** [comment]
I spent a little time thinking about if we could `include` an `Arrayable` mixin module in existing transform classes to achieve this behavior via composition. But I came back to thinking this is the safer, more expedient option, especially given that you have written it!

## RE: naming things being hard

Explode isn't the right place for it, because it doesn't create new rows, and that's how I've defined [the scope of Explode](https://lyrasis.github.io/kiba-extend/Kiba/Extend/Transforms/Explode.html). 

I would leave "Multival" out since it can also transform single value or blank fields to arrays.

As the searchable documentation is improving, I'm less concerned with nesting a bunch of transforms under one namespace, and am more into straightforward direct names. Like, I considered `Replace::FractionWithDecimal` or `Convert::FractionToDecimal` before settling on just `Fraction::ToDecimal`. It's particularly nice in use as `transform Fraction::ToDecimal`

I'd suggest `String::ToArray` but I have concerns about annoying conflicts when used in projects. (maybe not because Ruby `String` is a class, not a module. I run into this using the `Cspace::NormalizeForID` transform in a project where I have a `Cspace` module defined in the project to namespace jobs, and I have to do `transform Kiba::Extend::Cspace::NormalizeForID`, which defeats the purpose of the nice brief direct name...)

Maybe `StringValue::ToArray`?

## Other

A couple of other things that should really be documented in a "Contributor Guidelines" document, so I will write that up and link it in another comment when done.

**Comment by kspurgin** [comment]
@eightBitter Ok, https://lyrasis.github.io/kiba-extend/file.contributing.html

If you can consider renaming and the things covered in that document... then ping me for final review!

**Comment by eightBitter** [comment]
@kspurgin finally getting around to looking at this. I like `StringValue::ToArray`. I refactored my transform based on this and the contributor guidelines and added the tests to the yard documentation.

I did `git pull --rebase` to grab any changes from `main` and also had to do `git pull --rebase` on the upstream branch to be able to push my changes to the upstream branch. However, it looks like that has totally confused the PR and inserted an unintended commit into the history. Sometimes git annoys the hell outta me.

If you'd rather me make a clean branch (with only the refactored code) and PR, let me know.

**Review by kspurgin — APPROVED** [review]
Looks good. I'm going to squash and merge so the extra commits are no problem.

**Pull request merged**
